### ISSUE TITLE
Error trying to generate API Client with swagger.json 

### ISSUE THREAD

**Issue by artsai** [ShipEngine/shipengine-openapi#14]
HI,
I'm using NSwagStudio v 13.15.10.0 
I downloaded swagger.json from https://shipengine.github.io/shipengine-openapi/ 
There were errors in the file,
Line 9333 and Line 12027

Could you please try to check by test generating a client with what you guy provided? 
Thank you
Art

**Comment by semarj** [comment]
Hello @artsai. Can you post what lines those are for you? When I download the swagger from there I get 9333 is:
```            "readOnly": true,
            "allOf": [
--->          {
                "$ref": "#/components/schemas/weight"
              }
```
             
And 12027 is:
```          "allOf": [
            {
--->           "$ref": "#/components/schemas/rate%20estimate"
            }
          ]
```

Are those the same for you?

**Comment by artsai** [comment]
@semarj 
It's 9933 
```
       "properties": {
          "package_id": {
            "readOnly": true,
            "type": "integer",
            "format": "int32"
          },
--->          "description": "The package ID\n",
          "package_code": {
            "allOf": [
              {
                "$ref": "#/components/schemas/package_code"
              }
            ],
```

I use NSwagStudio to generate the API, its complaints about that line.  I moved "description" to the properties section, that will work. In the yaml file, it's line 7925-7926. 

![image](https://user-images.githubusercontent.com/3355296/158850953-7cc4057c-7346-4a76-90b1-4a04c6ef1c32.png)

As for "rate%20estimate"   in your YAML, it's 
![image](https://user-images.githubusercontent.com/3355296/158852594-74fccb01-48a0-4667-bd11-13c1d3d6390f.png)
so I just use space instead of "%20"

Since I would like to rely on the provided OpenAPI docs, I would like to know if you guys test creating API client from the docs?

**Comment by semarj** [comment]
Currently this doesn't happen. We'll take a look.

**Comment by semarj** [comment]
It looks like we do not test the client generation but you might consider using https://github.com/ShipEngine/shipengine-dotnet instead of generating the client. We will look at the SDK generation test on the next iteration of OpenApi specification generation.

**Comment by artsai** [comment]
I used https://github.com/ShipEngine/shipengine-dotnet as a guideline to build our own Partner API SDK as the Partner Open API specification wasn't provided, that is understandable. As for the Account operations APIs, the provided SDK doesn't have all of the endpoints implemented, so I was relying on the API documents for the generated client so that my team can quickly start configuring and testing ShipEngine Acccount API operations. At the moment, I do have the Account API generated after my manual fixes. The generated methods work for what I need at the moment. I may switch to extending missing implementations with the shipengine-dotnet if the generated client becomes unreliable.
