### ISSUE TITLE
Support OpenAPI tools that don't fully support additionalProperties

### ISSUE THREAD

**Issue by kendallb** [ShipEngine/shipengine-openapi#2]
It appears it is not working with SwaggerHub (I have opened a ticket with them), but it also does not work with AutoRest. When I run it with AutoRest I see the following, which seems to indicate something is broken in the configuration?

```
C:\src\snap\DataAccess\Modules\Shipping\ShipEngineClient>autorest config.yaml
AutoRest code generation utility [cli version: 3.0.6187; node: v12.18.3, max-memory: 8192 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      'C:\Users\kenda\.autorest\@autorest_core@3.0.6306\node_modules\@autorest\core\dist' (3.0.6306)
   Loading AutoRest extension '@microsoft.azure/autorest.csharp' (~2.3.79->2.3.84)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.55->2.3.55)
FATAL: Error parsing swagger file. Error converting value False to type 'AutoRest.Modeler.Model.Schema'. Path 'components.schemas.parse_address_request_body.additionalProperties', line 1, position 109890.
FATAL: AutoRest.Core.Logging.CodeGenerationException: Error parsing swagger file. Error converting value False to type 'AutoRest.Modeler.Model.Schema'. Path 'components.schemas.parse_address_request_body.additionalProperties', line 1, position 109890.
   at AutoRest.Modeler.SwaggerParser.Parse(String swaggerDocument) in /opt/vsts/work/1/s/src/SwaggerParser.cs:line 52
   at AutoRest.Modeler.Program.<ProcessInternal>d__2.MoveNext() in /opt/vsts/work/1/s/src/Program.cs:line 58
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NewPlugin.<Process>d__15.MoveNext()
  Error: Plugin imodeler1 reported failure.
```

**Comment by JamesMessinger** [comment]
This appears to be a bug in AutoRest.  Based on the error message, it appears that it doesn't support a boolean value for the `additionalProperties` keyword.  It seems to expect it to be a Schema object.

According to [the OpenAPI Specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#properties), the `additionalProperties` keyword can be a boolean or a Schema object.

There is an [issue in the AutoRest repo](https://github.com/Azure/autorest/issues/3439) that appears to be related to this problem.  It has some suggestions to resolve the issue.

**Comment by kendallb** [comment]
Well nothing is able to generate a client, as it fails on swaggerhub also. So while perhaps there is a bug, it’s common to most tools out there so likely you can fix it with changes to your schema?

**Comment by kendallb** [comment]
We are trying to get started with ShipEngine and the support folks couldn’t even generate a client library for me. Perhaps someone can fix the schema as it seems that additionalProperties=false is not really supported in the v3 spec?

https://groups.google.com/forum/m/#!msg/json-schema/Es0fEf3hj2Y/MxWmgercBAAJ

**Comment by JamesMessinger** [comment]
@kendallb - Here's a copy of the API definition with all `additionalProperties` keywords changed from booleans to objects. 

[openapi.yaml.txt](https://github.com/ShipEngine/shipengine-openapi/files/5017100/openapi.yaml.txt)

Please note that the OpenAPI ecosystem is [filled with tools](https://openapi.tools/) that vary greatly in their adherence to the spec.  Due to all these variances, it's not possible to support every tool, and interoperability between various tools can be tricky. It is often necessary to modify an OpenAPI definition to meet the needs of your preferred tools.

**Comment by kendallb** [comment]
Thanks. Given that there is some contention about whether false is supported there in the spec, it would make sense for your official specs to be changed to boolean objects so the new tools work correctly?

**Comment by JamesMessinger** [comment]
Yeah, I think it's probably safe to make the change.  We'll need to check a few different popular tools to make sure it doesn't break anything that's currently working.

**Comment by kendallb** [comment]
Hmm, it's still not working with either SwaggerHub or AutoRest. I get the following now when I try to generate it with AutoRest (with SwaggerHub I just get a generic error message). Got any ideas?

```
C:\src\snap\DataAccess\Modules\Shipping\ShipEngineClient>update
AutoRest code generation utility [cli version: 3.0.6187; node: v12.18.3, max-memory: 8192 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      'C:\Users\kenda\.autorest\@autorest_core@3.0.6306\node_modules\@autorest\core\dist' (3.0.6306)
   Loading AutoRest extension '@microsoft.azure/autorest.csharp' (~2.3.79->2.3.84)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.55->2.3.55)
FATAL: Error parsing swagger file. Unexpected character encountered while parsing value: [. Path 'components.schemas.schemas:109.default', line 1, position 147639.
FATAL: AutoRest.Core.Logging.CodeGenerationException: Error parsing swagger file. Unexpected character encountered while parsing value: [. Path 'components.schemas.schemas:109.default', line 1, position 147639.
   at AutoRest.Modeler.SwaggerParser.Parse(String swaggerDocument) in /opt/vsts/work/1/s/src/SwaggerParser.cs:line 52
   at AutoRest.Modeler.Program.<ProcessInternal>d__2.MoveNext() in /opt/vsts/work/1/s/src/Program.cs:line 58
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NewPlugin.<Process>d__15.MoveNext()
  Error: Plugin imodeler1 reported failure.
```

**Comment by kendallb** [comment]
I ended up using NSwag Studio and have been working on modifying their code base to support the way I want the client generator to work, as it works correctly. The Swagger folks admitted their tools are broken, but have no timeline for a fix.

Anyway, is this the right place to report issues with the spec? I am running into some issues with the spec saying certainly fields are required, but it would appear it comes over the wire as missing (null) (company_name in address validation is one so far). I have manually hacked my client mappings, but I am wondering how we can fix this in the spec?

**Comment by kendallb** [comment]
Created a pull request to fix the issues in the spec, and gonna close this one out as SmartBear just needs to fix their own tools.

**Comment by JamesMessinger** [comment]
I'm glad to hear that NSwag ended up working for you.  And we absolutely welcome any corrections to our API definition. You can file issues on this repo.  The API definitions in this repo are generated by our internal build process, so merging a PR won't work because it'll just get overwritten on the next build.  But an issue can serve as a to-do item for us to correct our internal definition, which will then be reflected here.
